---
title: "PS270 Final Project"
author: "Maggie Claussen"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to Artificial Intelligence infrastructure implementation in communities across the United States. I would like to look at data centers, AI companies being trademarked, and public opinion data on the local response. 

## Hypothesis, Research Question, and IV/DV's

I will be using the following dataset from Pew Research Center about “How the U.S. Public and AI Experts View Artificial Intelligence.” I am planning to switch my focus away from data center infrastructure and towards a public opinion analysis as the local response is interesting to me. I plan to continue to search for more current datasets that include multiple variables for the cause. My current research question is: How does the public opinion shift around AI due to occupation or attitude of the current company one is at? I would love to acknowledge education as well—thinking about how teachers and students are impacted by AI development. Aspects of capitalism will be a key part of this. Does capitalism have an impact on public opinion? I hypothesize that if one’s opinion on the use of AI (especially for the purpose of economic efficiency) is dependent on the industry they are going into or in currently. The explanatory variable is the industry, which would be measured by survey research, while the outcome variable is the opinion or belief that they hold on AI. This dataset provides a variety of survey questions that assess public opinion of those polled. Public opinion research is tough because it is so nuanced and reducing bias in survey questions is nearly impossible. The way our brains process information is entirely dependent on our previous experiences. However, I would like to see if there is a systemic cause for AI opinions due to the rapid development of LLM’s in countless industries. If the data shows that STEM fields, for example, have a higher support rate for AI usage, we would know that there is a causation that those in that field will make different political decisions surrounding AI development (i.e. data centers, local investments, etc.). If there is wide variation of opinions in the field, my hypothesis would be disproven.

https://www.pewresearch.org/internet/2025/04/03/how-the-us-public-and-ai-experts-view-artificial-intelligence/ 

```{r}
library(readr)
ATP_W152 <- read_csv("~/Downloads/W152_Aug24/ATP W152.csv")
View(ATP_W152)
```

